const linksKeywords = [
  'doc',
  //'document',
  // 'customer',
  // 'endpoint',
  // 'requirements',
  // 'service',
  // 'docs',
  // 'manual',
  // 'guide',
  // 'api',
  // 'reference',
  // 'specification',
  // 'help',
];
